spring:
  application:
    name: userCenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sui
    username: root
    password: 1234

server:
  port: 8080

